
obj-m := i2c-devs.o

i2c-devs-y := i2c_devs.o gpio.o i2c.o lcd.o rtc.o \
							../test/unit/add_tests.o ../test/unit/test_gpio.o \
							../test/unit/test_i2c.o ../test/unit/test_lcd.o \
  						../test/unit/test_rtc.o

ccflags-y +=  -I${obj}/../include \
						  -I${obj}/../../shared \
						  -I${obj}/../test/unit \
							-I${obj}/../../../../build/yocto-4.14.98/ktf/usr/include							
